create table if not exists articles (
  id bigint generated by default as identity primary key,

  title text not null,

  slug text unique not null,

  summary text,

  content text not null,

  category text default 'news',

  language text default 'bn',

  source_title text,

  source_url text,

  image_url text,

  seo_title text,

  seo_description text,

  published boolean default false,

  published_at timestamptz,

  created_at timestamptz default now()
);


create index if not exists articles_published_idx
on articles(published, published_at desc);


create table if not exists rss_sources (
  id bigint generated by default as identity primary key,

  name text not null,

  url text not null,

  category text default 'news',

  active boolean default true,

  created_at timestamptz default now()
);


create table if not exists site_settings (
  id bigint generated by default as identity primary key,

  setting_key text unique not null,

  setting_value text,

  updated_at timestamptz default now()
);


insert into site_settings
(setting_key, setting_value)
values
('auto_publish', 'true')
on conflict (setting_key)
do nothing;


insert into site_settings
(setting_key, setting_value)
values
('daily_category', 'news')
on conflict (setting_key)
do nothing;


insert into rss_sources
(name, url, category)
values
(
  'BBC News',
  'https://feeds.bbci.co.uk/news/rss.xml',
  'news'
)
on conflict do nothing;


alter table articles enable row level security;

alter table rss_sources enable row level security;

alter table site_settings enable row level security;


create policy "public can read published articles"
on articles
for select
to anon
using (published = true);


create policy "public can read active rss sources"
on rss_sources
for select
to anon
using (active = true);
